name: 'Setup Next JS Environment'
description: 'Initializes dependencies & caches for Next JS'

runs:
  using: "composite"
  steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
      
    # Cache is tracked by package or source code changes from the checked out repository
    - name: Apply NPM & Next JS Cache
      id: npm-nextjs-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
        
    # Pulls Node Module packages from cache if exists
    - name: Install NPM Dependencies
      shell: bash
      run: npm ci